In [52]:

import pickle
from utils import numpy_arr_to_str

In [46]:

with open("DL_pretrained_model/predator_q_table.pickle", "rb") as f:
    res = pickle.load(f)

In [47]:
import torch
import numpy as np

In [48]:
a = [[2,1,2], [2,2,1], [0,2, 1]]

In [49]:
arr = np.array(a, dtype=np.int64)

arr

array([[2, 1, 2],
       [2, 2, 1],
       [0, 2, 1]])

In [55]:
res[numpy_arr_to_str(np.array(arr))].__class__


list

In [51]:
list(res.keys())[0]

'012|120|211'

tensor([[2., 1., 2.],
        [2., 2., 1.],
        [0., 2., 1.]])

In [44]:
res[torch.tensor(np.array(arr, dtype=np.float32), dtype=torch.float32)]

KeyError: tensor([[2., 1., 2.],
        [2., 2., 1.],
        [0., 2., 1.]])

In [43]:
torch.tensor(np.array(arr, dtype=np.float32), dtype=torch.float32)




tensor([[2., 1., 2.],
        [2., 2., 1.],
        [0., 2., 1.]])